app = "telegram-video-bot"
primary_region = "sin"

[build]
  image = "python:3.10"

[env]
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
